name: Auto-merge Dependabot PRs

on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@66ad0bfc3e6d109341d369a0a06a1f426a5c265e # v2.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-merge minor and patch updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
